#!/usr/bin/env python2

# Usage: ./pygmentize-outerline -O full,style=native -o full.html ../../examples/full.lne

from pygments.cmdline import main
from pygments.lexers._mapping import LEXERS
from outerline import OuterlineLexer

LEXERS[OuterlineLexer.__name__] = (
    OuterlineLexer.__module__,
    OuterlineLexer.name,
    tuple(OuterlineLexer.aliases),
    tuple(OuterlineLexer.filenames),
    tuple(OuterlineLexer.mimetypes))

main()

# vim:sw=4
